version: '3.8'

services:
    postgres:
        image: postgres:13
        environment:
            - POSTGRES_DB=market_db
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin123
        ports:
            - 5432:5432
        volumes:
            - ./postgres_data:/var/lib/postgresql/data

    pgadmin:
        image: dpage/pgadmin4
        environment:
            - PGADMIN_DEFAULT_EMAIL=admin@mail.com
            - PGADMIN_DEFAULT_PASSWORD=root
        ports:
            - 5050:80
    app:
        build: .
        restart: always
        ports:
        - "3000:3000"
        command:
        - sh
        - -c
        - |
            npm run dev
